### ISSUE TITLE
Event .on() not working?

### ISSUE THREAD

**Issue by fabianogaldino** [ankurk91/vue-web-storage#12]
I can't get the .on event to respond to the on change

https://jsfiddle.net/kw8crs23/

**Comment by ankurk91** [comment]
I will debug it, will report it back soon.

These events are for cross tab communication

**Comment by ankurk91** [comment]
@fabianogaldino 
As said in above comment. These events are not regular events, these events are for cross tab communication.

Open this jsfiddle in two tabs and you will notice the events listeners are being fired.

Read more:
https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent
