### ISSUE TITLE
String is saved with quotes 

### ISSUE THREAD

**Issue by piotrmachacki** [ankurk91/vue-web-storage#17]
Why every simple string is saved with quotes?

Example:
`this.$localStorage.set('name', 'john')` -> "john" (with ")
`localStorage.setItem('name', 'john')` -> john (without ")

I think it is not necessary to use `JSON.stringify` on string.

**Comment by ankurk91** [comment]
This is what happening behind the scenes
```js
localStorage.setItem("name",JSON.stringify("john"))

localStorage.getItem("name")
// "\"john\""

JSON.parse(localStorage.getItem("name"))
// "john"

```

i dont think the library is behaving odd
