### ISSUE TITLE
Error Unexpected token in JSON

### ISSUE THREAD

**Issue by machinek56** [ankurk91/vue-web-storage#2]
Hi!
I've using this plugin in my project and encountered such issue.

When i write some  property to sessionStorage like `sessionStorage.setItem('key', 'value')` and then try read it using vue-web-storage method - `Vue.$storage.get('key)` i got such error 

![image](https://user-images.githubusercontent.com/12989125/36480711-5be53c2c-171e-11e8-9bdb-c5c3230cf900.png)

I found that it happens when i try to read property without quotes. 

![image](https://user-images.githubusercontent.com/12989125/36480725-6e0c14fc-171e-11e8-8592-2ab4584032db.png)

When property stored in sessionStorage in double quotes all is ok.

Can you add ability to read properties from sessionStorage without double quotes and such errors?

**Comment by ankurk91** [comment]
You should store and retrieve in same way.

**Comment by machinek56** [comment]
Hmm, and there is no solution this issue, except you provided?

**Comment by ankurk91** [comment]
Can you share me your full example ?
I am already sending actual value when failed to parse, see
https://github.com/ankurk91/vue-web-storage/blob/32491a41473f4c9a39011a8989d2d80f52b9e1c5/src/util.js#L1-L9

It shows you error in development only.

**Comment by machinek56** [comment]
Yes, value is returned, but errors are annoying.. so i will use native methods or write properties using JSON.stringify().

Thanks!
