### ISSUE TITLE
Expiration and default value in get() method

### ISSUE THREAD

**Issue by herenickname** [ankurk91/vue-web-storage#3]
1) Can you add support for the expiration date of the entry?
2) Can you add a default value to `.get()` if it is not found in the storage?

**Comment by ankurk91** [comment]
I want to keep this library simple.
These features you mentioned exists in other libraries already that makes them heavey and bloated.

The default value for get method can be implemented in your app itself.

`
Vue.$storage.get("key") || defaultValue.
`

**Comment by ankurk91** [comment]
The default value option has been added in v2.1.0
