### ISSUE TITLE
Allow multiple drivers

### ISSUE THREAD

**Issue by rtuk** [ankurk91/vue-web-storage#4]
Currently the plugin is added to the Vue instance as $storage
This means that you cannot use local storage and session storage at the same time.
It would be very useful to have the driver name be the instance variable name as well:
So for localStorage it would be Vue.prototype.$localStorage and for sessionStorage it would be Vue.protoype.$sessionStorage
This way you will be able to add the plugin twice:

```javascript
import Vue from 'vue';
import Storage from 'vue-web-storage';  
Vue.use(Storage, {
  prefix: 'your_app_name',// default `app_`
  driver: 'local', // default 'local'
})
Vue.use(Storage, {
  prefix: 'your_app_name',// default `app_`
  driver: 'session', // default 'local'
})
```

and access the different storages using this.$localStorage and this.$sessionStorage

**Comment by ankurk91** [comment]
I like this idea, i will look into it.

**Comment by ankurk91** [comment]
Vue does not allow to use `Vue.use` for a plugin twice. It has to be called once.

What about this
```js
Vue.use(Storage, {
  prefix: 'your_app_name',
  driver: 'both', 
})
```
When specified `both` , this will register both `this.$localStorage` and `this.$sessionStorage`

Other options welcome.


You can track implementation on [next](https://github.com/ankurk91/vue-web-storage/tree/next) branch

* [x] Updates test
* [x] Update docs

**Comment by rtuk** [comment]
Maybe allow driver to be an array:

```javascript
Vue.use(Storage, {
  prefix: 'your_app_name',
  driver: ['local','session'], 
})
```

That way you will be ready for any additional storage mechanisms that might be added in the future

**Comment by ankurk91** [comment]
Another approach would be
```js
// Supply array of objects
Vue.use(Storage, [
{
  prefix: 'front_end', // optional
  driver: 'session',  
  name : 'appStorage' // will auto prefix $ // optional // default `storage`
},
{
  prefix: 'admin_panel', // optional
  driver: 'session', 
  name : 'adminStorage' // will auto prefix $ // optional // default `storage`
},
]);
// OR  single object
Vue.use(Storage, {
  prefix: 'app_',
  driver: 'local', 
 name : 'storage'
});
```

**Comment by georgehanson** [comment]
@ankurk91 an array of objects would be the best approach I think. If for the same prefix you have multiple drivers, it can cause problems as the developer might be thinking something is in session but it's actually in vice-versa. Setting a driver per prefix is safer.

**Comment by ankurk91** [comment]
I want it to be backward compatible.

I also want to allow developers to rename the instance key so that it won't conflict with other libraries.

I can understand that when passing multiple object without specifing `name` will ended up only one driver. 
I will documentation it that each object should have a unique `name` property value.

**Comment by rtuk** [comment]
> I can understand that when passing multiple object without specifing name will ended up only one driver.
> I will documentation it that each object should have a unique name property value.

@ankurk91 this could be easily checked within the code as well

**Comment by ankurk91** [comment]
v3.0.0 is released, see

https://github.com/ankurk91/vue-web-storage/blob/master/UPGRADING.md
to upgrade
