### ISSUE TITLE
hasKey doesn't work

### ISSUE THREAD

**Issue by Tusko** [ankurk91/vue-web-storage#8]
https://github.com/ankurk91/vue-web-storage/blob/eacce996035daede7862d472960041d58be1f42c/src/storage.js#L60

I have a problem with `hasKey` method
http://cl.ly/c4286b58284d

**Comment by ankurk91** [comment]
How are you using this package?
Can you share the package installation and configuration code?

**Comment by ankurk91** [comment]
Your screenshot says that `hasKey` method is not available on undefined.

**Comment by Tusko** [comment]
In `app.js` (main Vue file added the code:


    import Storage from 'vue-web-storage';  
    Vue.use(Storage); 
    
    Vue.use(Storage, {
      prefix: 'm_admin_',
      drivers: ['session','local'], 
    });

Tried to use `Vue.$localStorage` and `this.$localStorage`.
The first and second methods are `undefined` (checked using a debugger).

**Comment by ankurk91** [comment]
I could not re-produce the issue, check

https://codesandbox.io/s/w7ov5728yk

Some thing is wrong with your code.
